ポーズ機能を実装してみました。
EbiseLutica/sukiteto pull request #18
Opened 2024-01-04 16:27 UTC by nice714106tall

2024-01-05 00:42 UTC, EbiseLutica requested changes
@nice714106tall PRありがとうございます！レビューしましたので修正対応お願いします。

なお、機能追加時は仕様の齟齬があると良くないので、今後は先に [Issue](/EbiseLutica/sukiteto/issues) を立てて議論を進めてからPRをお願いします。

2024-01-05 00:42 UTC, EbiseLutica commented on src/Scenes/GameScene.cs
> +            Audio.PlayOneShotAsync(Resources.SfxLineClear);
実装が古いのに戻ってしまっているので戻してください

```suggestion
            Audio.PlayOneShotAsync(Resources.GetLineClearSound(e));
```

2024-01-05 00:42 UTC, EbiseLutica commented on src/Scenes/GameScene.cs
> +        }
ifの方で `return;` しているので、 `else` 句は不要です

2024-01-05 00:42 UTC, EbiseLutica commented on src/Scenes/GameScene.cs
> +                //Audio.PlayOneShotAsync(Resources.SfxMove); //ソフトドロップ中うるさいのでコメントアウト
Issue等での事前相談なしに仕様を変更するべきではないので、この行は戻してください～

2024-01-05 00:42 UTC, EbiseLutica commented on src/Services/GameService.cs
> +		PlaceBlock(BlockPosition.X, BlockPosition.Y, CurrentShape, CurrentBlockColor);
PRの内容に合わない変更と思われるので削除をお願いします。

2024-01-07 14:04 UTC, nice714106tall commented on src/Scenes/GameScene.cs
> +        }
修正しました。

2024-01-07 14:04 UTC, nice714106tall commented on src/Scenes/GameScene.cs
> +                //Audio.PlayOneShotAsync(Resources.SfxMove); //ソフトドロップ中うるさいのでコメントアウト
戻しました。

2024-01-07 14:06 UTC, nice714106tall commented on src/Services/GameService.cs
> +		PlaceBlock(BlockPosition.X, BlockPosition.Y, CurrentShape, CurrentBlockColor);
291行目は削除しました。
292行目(既存コード)を消したら置いたブロックが消えてしまうため残しています。

2024-01-07 14:09 UTC, nice714106tall commented on src/Scenes/GameScene.cs
> +            Audio.PlayOneShotAsync(Resources.SfxLineClear);
897eb0のバージョンを基にして書いてしまっていたので、修正するとResourceLoaderのエラーが出てしまいます。
一旦そのままにしています。

2024-04-13 22:22 UTC, closed without merging